assignment_data = [
    {
        "ID": "E1",
        "Historia de Crédito": "Ruim",
        "Dívida": "Alta",
        "Garantia": "Nenhuma",
        "Renda": "$0 a $15k",
        "Risco": "Alto",
    },
    {
        "ID": "E2",
        "Historia de Crédito": "Desconhecida",
        "Dívida": "Alta",
        "Garantia": "Nenhuma",
        "Renda": "$15 a $35k",
        "Risco": "Alto",
    },
    {
        "ID": "E3",
        "Historia de Crédito": "Desconhecida",
        "Dívida": "Baixa",
        "Garantia": "Nenhuma",
        "Renda": "$15 a $35k",
        "Risco": "Moderado",
    },
    {
        "ID": "E4",
        "Historia de Crédito": "Desconhecida",
        "Dívida": "Baixa",
        "Garantia": "Nenhuma",
        "Renda": "$0 a $15k",
        "Risco": "Alto",
    },
    {
        "ID": "E5",
        "Historia de Crédito": "Desconhecida",
        "Dívida": "Baixa",
        "Garantia": "Nenhuma",
        "Renda": "Acima de $35k",
        "Risco": "Baixo",
    },
    {
        "ID": "E6",
        "Historia de Crédito": "Desconhecida",
        "Dívida": "Baixa",
        "Garantia": "Adequada",
        "Renda": "Acima de $35k",
        "Risco": "Baixo",
    },
    {
        "ID": "E7",
        "Historia de Crédito": "Ruim",
        "Dívida": "Baixa",
        "Garantia": "Nenhuma",
        "Renda": "$0 a $15k",
        "Risco": "Alto",
    },
    {
        "ID": "E8",
        "Historia de Crédito": "Ruim",
        "Dívida": "Baixa",
        "Garantia": "Adequada",
        "Renda": "Acima de $35k",
        "Risco": "Moderado",
    },
    {
        "ID": "E9",
        "Historia de Crédito": "Boa",
        "Dívida": "Baixa",
        "Garantia": "Nenhuma",
        "Renda": "Acima de $35k",
        "Risco": "Baixo",
    },
    {
        "ID": "E10",
        "Historia de Crédito": "Boa",
        "Dívida": "Alta",
        "Garantia": "Adequada",
        "Renda": "Acima de $35k",
        "Risco": "Baixo",
    },
    {
        "ID": "E11",
        "Historia de Crédito": "Boa",
        "Dívida": "Alta",
        "Garantia": "Nenhuma",
        "Renda": "$0 a $15k",
        "Risco": "Alto",
    },
    {
        "ID": "E12",
        "Historia de Crédito": "Boa",
        "Dívida": "Alta",
        "Garantia": "Nenhuma",
        "Renda": "$15 a $35k",
        "Risco": "Moderado",
    },
    {
        "ID": "E13",
        "Historia de Crédito": "Boa",
        "Dívida": "Alta",
        "Garantia": "Nenhuma",
        "Renda": "Acima de $35k",
        "Risco": "Baixo",
    },
    {
        "ID": "E14",
        "Historia de Crédito": "Ruim",
        "Dívida": "Alta",
        "Garantia": "Nenhuma",
        "Renda": "$15 a $35k",
        "Risco": "Alto",
    },
    {
        "ID": "E15",
        "Historia de Crédito": "Boa",
        "Dívida": "Baixa",
        "Garantia": "Adequada",
        "Renda": "Acima de $35k",
        "Risco": "Baixo",
    },
    {
        "ID": "E16",
        "Historia de Crédito": "Desconhecida",
        "Dívida": "Baixa",
        "Garantia": "Adequada",
        "Renda": "$15 a $35k",
        "Risco": "Baixo",
    },
    {
        "ID": "E17",
        "Historia de Crédito": "Boa",
        "Dívida": "Alta",
        "Garantia": "Adequada",
        "Renda": "$15 a $35k",
        "Risco": "Baixo",
    },
    {
        "ID": "E18",
        "Historia de Crédito": "Ruim",
        "Dívida": "Baixa",
        "Garantia": "Adequada",
        "Renda": "$15 a $35k",
        "Risco": "Moderado",
    },
    {
        "ID": "E19",
        "Historia de Crédito": "Boa",
        "Dívida": "Alta",
        "Garantia": "Adequada",
        "Renda": "$0 a $15k",
        "Risco": "Moderado",
    },
    {
        "ID": "E20",
        "Historia de Crédito": "Ruim",
        "Dívida": "Alta",
        "Garantia": "Adequada",
        "Renda": "$15 a $35k",
        "Risco": "Moderado",
    },
]
